# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  database: myapp_development
  username: myapp 
  password: qwe
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: myapp_test
  username: myapp  
  password: qwe
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: myapp_production
  username: myapp 
  password: qwe 
  host: localhost
